#!/bin/bash

# See: https://github.com/yoomlam/ruby-in-jupyter/blob/master/postBuild
set -ex
PATH="`ruby -e 'puts Gem.user_dir'`/bin:$PATH"
gem install --user-install ffi-rzmq
gem install --user-install iruby --pre
iruby register --force

git config --global user.name "Mariah A. Knowles"
git config --global user.email "snotskie@gmail.com"
