#!/bin/bash

# Configure git defaults
git config --global user.name "jovyan"
git config --global user.email "jovyan@mybinder"

# Configure ruby for jupyter
# See: https://github.com/yoomlam/ruby-in-jupyter/blob/master/postBuild
set -ex
PATH="`ruby -e 'puts Gem.user_dir'`/bin:$PATH"
gem install --user-install ffi-rzmq
# gem install --user-install iruby --pre
gem install --user-install pry-byebug
gem install --user-install json
gem install --user-install date
gem install --user-install csv
# iruby register --force
